version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - node -v
      - npm -v
      - npm ci
  pre_build:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: dist
